server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location /api/products { proxy_pass http://product-service:4001/products; }
    location /api/cart { proxy_pass http://cart-service:4002/cart; }
    location /api/orders { proxy_pass http://order-service:4003/orders; }
    location /api/payments { proxy_pass http://payment-service:4004/payments; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
