sonar.organization=aniljadhavmca
sonar.projectKey=aniljadhavmca_shop-easy
sonar.projectName=Shop Easy

sonar.sources=frontend/src,product-service,order-service

sonar.exclusions=\
  **/node_modules/**,\
  **/build/**,\
  **/dist/**,\
  **/*.test.js,\
  **/*.spec.js,\
  **/coverage/**,\
  **/Dockerfile,\
  **/*.sql,\
  **/observability-service/**,\
  **/db-init/**,\
  **/terraform/**,\
  **/docs/**,\
  **/package-lock.json

sonar.sourceEncoding=UTF-8
sonar.javascript.file.suffixes=.js,.jsx
sonar.css.file.suffixes=.css
